### ISSUE TITLE
Add photo to note

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hauke96/GeoNotes#11]
GeoNotes I had from [Izzy Repo](https://apt.izzysoft.de/fdroid/index/apk/de.hauke_stieler.geonotes)

a #musthave repo, in my opinion

In the README.md it says that images should also be added.
that would be fantastic. so far i always see what i can enter, make notes and add the picture and then have to write where the picture is. it would be easier that way.

i have made 10000 entries in openstreetmap in the last 2 years (2018 to 2020). that's why i find GeoNotes so awesome.

**Comment by hauke96** [comment]
This will definitely be the feature of this app I'll work on.

However, notes will stay on your device, so this app doesn't and won't create note on osm.org. There are other apps for that where you can add osm.org-notes with photos (e.g. [StreetComplete](https://github.com/westnordost/StreetComplete/)).

**Comment by mondlicht-und-sterne** [comment]
yes I mean I can use GeoNotes very well, because I map so much

**Comment by Strubbl** [comment]
I really like that it keeps the notes local on the device, because some people do not like the "spam" on osm.org notes with pictures if you create more in a short time frame. So if i could take pictures and attach it to notes, this would make note taking a lot faster cause i have less to type.
