### ISSUE TITLE
location on location off

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hauke96/GeoNotes#12]
If I have my location on and open GeoNotes, I still see your Hamburg. I then first have to zoom out osm far , then swipe to me and then I see my location green. and if I open GeoNotes again later, I still see your Hamburg again despite my location.
so why should I turn on my location when I have to zoom out and swipe anyway, regardless of whether I have my location on or off?

**Comment by hauke96** [comment]
It's still optional if you turn your phones location service on or off ;)

But the feature you want may be something like this(?): Remember the last shown location and zoom to that location when I launch the app.

**Comment by barnesl** [comment]
To add to this, if the location is on, can there be an button to "zoom" to your current location? To keep inline with your no UI overhead philosophy, there could be a setting to turn this button on and off.

**Comment by hauke96** [comment]
The location is now stored with every zoom and scroll on the map. After restarting the map, this location is restored.

This will be part of release 1.1.0.
