### ISSUE TITLE
View of Notes

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hauke96/GeoNotes#13]
let's say you take notes in dresden, frankfurt/oder, berlin, chemnitz and hamburg.

when i start the app the second time, i only see your hamburg. so i always have to zoom out and then swipe back and forth.

so GeoNotes still needs a view of the notes, then you could jump there faster.

**Comment by hauke96** [comment]
You mean a list of all notes by "view of the notes"?

**Comment by mondlicht-und-sterne** [comment]
yes otherwise I am only busy scrolling

**Comment by hauke96** [comment]
@mondlicht-und-sterne So in #21 another user mentioned the idea of lists. Maybe you have also some feedback on that?

**Comment by hauke96** [comment]
I added a list view of all notes (new icon in the toolbar), this will probably be published via F-Droid soon.
