### ISSUE TITLE
Export notes

### ISSUE THREAD

**Issue by dpalacio** [hauke96/GeoNotes#22]
It would be very helpful to import notes on JOSM. Maybe export in CSV format?
https://wiki.openstreetmap.org/wiki/JOSM/Plugins/OpenData#Tabular_files_.28CSV.2C_XLS.2C_ODS.29

Thank you for GeoNotes! :)

**Comment by hauke96** [comment]
Sounds reasonable to me. But I would rather export notes as GeoJson because it's a more standard and widely used format for geo stuff. You also don't need any plugins for GeoJson and a lot of other applications are able to understand GeoJson as well.

**Comment by dpalacio** [comment]
I think an import option should be considered as well. Imagine if I had a lengthy collection of notes I wouldn't be able to let go and attempted to test the release you posted recently. I would have lost all my notes.

**Comment by hauke96** [comment]
I think I get your point here. If it's very simple to also import stuff, I'll add it, otherwise I'll probably create a separate issue. But I think an import option shouldn't be too difficult to add as well.
