### ISSUE TITLE
Create note at current position

### ISSUE THREAD

**Issue by dpalacio** [hauke96/GeoNotes#24]
I'm not sure if this is already implemented, it seems not.
I find it very imprecise to place notes with a finger without reliable references. Often the current user position is the best data available when you can walk around the point of interest. 

I wish we could create a note by tapping the location cursor. This note would be created using the current GPS location.

**Comment by hauke96** [comment]
I think that would be possible ;)

**Comment by hauke96** [comment]
I added this to a small release `v1.2.1`. You now have a new setting, you can activate (it's called "Snap note to GPS location"). It may take a while until it's available in F-Droid. You also can download the signed APK file and install it manually: https://github.com/hauke96/GeoNotes/releases/tag/v1.2.1

**Comment by hauke96** [comment]
Oh and also: Please give me feedback how the snapping works and if it's sensitive enough or too sensitive.

**Comment by dpalacio** [comment]
It seems to be good. I'll test more and report if I change my mind.
