### ISSUE TITLE
GeoNotes asks for camera and media access permissions repeatedly after refusal

### ISSUE THREAD

**Issue by dpalacio** [hauke96/GeoNotes#25]
Android version: 10

On startup, because of the new media features, GeoNotes asks for some permissions. If refused by the user, it will keep asking until it is allowed.

What should happen:
GeoNotes should ask for permission only when a feature is actually used. And if refused, it should fail gracefully. It may ask for permission when the user triggers it again.

**Comment by hauke96** [comment]
The `TODO`s already exist in the code, but yeah, that's currently not the way it should work.

**Comment by dpalacio** [comment]
I had to report it, just in case ;)
