### ISSUE TITLE
Fine tune note position by dragging Move button

### ISSUE THREAD

**Issue by dpalacio** [hauke96/GeoNotes#28]
Finger tapping is very imprecise, thus moving a note by tapping on a different place is too. A note position could be corrected with very small displacements by dragging it. A candidate for a drag target/trigger is the move button. When tapped, tap on the map to move; when dragged, drag the note with it.

**Comment by hauke96** [comment]
So the move button already exists. I would simply replace the current behavior with the one of OsmAnd: The note stays in the middle of the screen and you simply move the map behind the note.

**Comment by dpalacio** [comment]
I was thinking of moving the note itself and OsmAnd isn't the best example of usability but, I don't really have a good reason to fight against that approach.

**Comment by IpswichMapper** [comment]
> So the move button already exists. I would simply replace the current behavior with the one of OsmAnd: The note stays in the middle of the screen and you simply move the map behind the note.

yes this seems like a good idea.

**Comment by hauke96** [comment]
Done in version 1.4.1
