### ISSUE TITLE
can't attach photo to note. Android 4.1.1

### ISSUE THREAD

**Issue by brebeneskul** [hauke96/GeoNotes#32]
"attach photo" button ask a camera app to choose:
- native camera app crashes after confirmation of the taken photo;
- opencamera (from f-droid) says _"storage accessing error"_;
(both apps works fine then run from a system launcher, but have no permission to write to SD, when run by a GeoNotes).

GeoNotes was downloaded from f-droid and from github v1.3.1, installed to SD. Attempt to make it system app was unsuccessful.
Lenovo P770; Android 4.1.1 (however, rooted, extremely customized, cluttered.. so, may be the problem here..)

**Comment by hauke96** [comment]
Hi, thanks for the bug report :)

This is actually a bug, I was able to reproduce it on a virtual machine. There will be a new release in the next couple of days.

**Comment by hauke96** [comment]
I added the release 1.3.2 which will be present in the F-Droid within a couple of days (depending how soon they update their store). The APK bundle can be downloaded directly from the [release-section](https://github.com/hauke96/GeoNotes/releases/tag/v1.3.2).

If the bug still occurs, please let me know here.
