### ISSUE TITLE
The menu is white on white

### ISSUE THREAD

**Issue by opk12** [hauke96/GeoNotes#35]
The menu entries `List of notes` and `Settings` are white text on white background. They are temporarily readable as white text on grey background, while they are being long tapped.

This is on a Samsung Galaxy J5 with Android 7.

**Comment by hauke96** [comment]
Hmm, everything looks fine so far on my device and also on all android emulators I use.

* Do you have a screenshots showing the problem?
* Do you have any themes installed/applied on your phone which may change default colors of text/backgrounds?

**Comment by opk12** [comment]
I do not have any themes or graphic customization on this phone.

![screenshot](https://user-images.githubusercontent.com/40740650/124355280-8bebb580-dc10-11eb-9252-844dc8144a66.png)

**Comment by hauke96** [comment]
Thanks for the screenshot, that's definitely a theming issue of GeoNotes.

**Comment by hauke96** [comment]
Fixed in 1.4.1
