### ISSUE TITLE
Drop down menu text is unreadable

### ISSUE THREAD

**Issue by Seaviator** [hauke96/GeoNotes#38]
Manufacturer: Fairphone
Model: FP3
Device: FP3
SDK-Version: 29
GeoNotes-Version: 1.4.0

The text of the drop down menu in the top right hand corner of the screen has a white font and as a result is unreadable.

**Comment by hauke96** [comment]
Hi, thanks for reporting this bug, which already has been fixed (#35) and the fix has already been released. However it always takes a few days until the new version is available on F-Droid.
