### ISSUE TITLE
Ability to rotate the map

### ISSUE THREAD

**Issue by opk12** [hauke96/GeoNotes#42]
I sometimes find myself rotating the phone just to grasp where to place the note correctly. It would be convenient to rotate the map with the fingers. For example, I collect points of interest to upstream to OSM, so an inaccurate position "at" a non-squarish intersection will not work for me; I need to know which branch is the right one.

**Comment by hauke96** [comment]
Thanks for the suggestion. Making the map rotatable with two fingers is easy but I haven't figured out yet how to reset the rotation. I would like to do that via the compass rose but unfortunately that's quite tricky. Maybe I find a solution for that.

**Comment by hauke96** [comment]
Found a solution and created the release 1.4.2. It will be available on F-Droid in the next couple of days.

**Comment by opk12** [comment]
Many thanks!
