### ISSUE TITLE
The phone's Back button does not save the settings

### ISSUE THREAD

**Issue by opk12** [hauke96/GeoNotes#43]
For any other app on this phone, tapping the phone's physical Back button while being in the settings panel saves the changes. This was confusing at first, but it is not really an issue for me, now that I know it. So I thought I would leave a mention, even if I'm not personally interested in seeing this to change.

**Comment by hauke96** [comment]
Thanks for this issue as well! I never used the back-button in GeoNotes to be honest. This was an easy fix and will be released together with #43 next week.
