### ISSUE TITLE
application/geo+json

### ISSUE THREAD

**Issue by opk12** [hauke96/GeoNotes#45]
Exporter.java [does](https://github.com/hauke96/GeoNotes/blob/d41d76fb5e38d9a0510912d7aa64c325030cc483/app/src/main/java/de/hauke_stieler/geonotes/export/Exporter.java#L37) `setType("application/json")`. Should the MIME type be `application/geo+json` in theory? Would that change the list of share targets (I share to Element or other chat app for easy sharing to the PC or other phone)?

**Comment by hauke96** [comment]
It may change the list of target apps but I haven't noticed any difference on my devices and emulators between `json` and `geo+json`. However I changed it to ` geo+json` maybe someone will benefit from it.
