### ISSUE TITLE
`geonotes:note` with newlines

### ISSUE THREAD

**Issue by SiIky** [hauke96/GeoNotes#50]
I think I found a bug -- or I'm using GeoNotes wrong.

If I create a note with e.g. the text

> this is
> a note

The exported JSON file will have the following entry:

```
				"geonotes:note": "this is
a note",
```

Which is not valid JSON (notice the non-escaped newline), and because of it JOSM can't load it.
As a workaround, I'm "manually" fixing these with my text editor.

Also, I imagine this is more general than just the newline.
I tried creating a note with `"`, however, and GeoNotes serialised it as `'` (`"geonotes:note": "'",`), which is valid JSON, but still unexpected to me.

**Comment by hauke96** [comment]
Hi, you're not using GeoNotes wrong ;) this seem actually to be a bug. Thanks for reporting it.

**Comment by hauke96** [comment]
I changed the whole way of how the GeoJson is created and also created unit tests for your cases. The problem should be fixed within the next release.

Also note: Due to #46 I renamed the fields, basically just dropped the `geonotes:` prefix of the property names.

**Comment by SiIky** [comment]
Very nice, thanks for the quick fix!
