### ISSUE TITLE
Delete all notes

### ISSUE THREAD

**Issue by Eiim** [hauke96/GeoNotes#56]
I use GeoNotes to quickly note the location of a POI to later export and edit in OSM. Over time, I've built up many (~100) of these notes, which makes figuring out which notes are the ones I need more cumbersome when I export them. It would be nice to be able to have a simple delete all button somewhere to reset my notes.

Thanks for making this app!

**Comment by hauke96** [comment]
Sound like a good idea to have such a button. Until I have implemented this, you can remove all notes using the "Clear data" button in the normal android settings menu of the app (the menu where you can also clear the cache or uninstall the app).

**Comment by hauke96** [comment]
I added such a delete-all-button in the note list. This will be part of the 1.4.4 release.

**Comment by Eiim** [comment]
Thank you!
