### ISSUE TITLE
setting the label by holding your finger

### ISSUE THREAD

**Issue by OmlineEditor** [hauke96/GeoNotes#57]
add to the settings a way to set a placemark on the map - **_put your finger and hold it_**.
now sometimes I just touch the map and a window automatically appears for entering a label. this is inconvenient. it is necessary to delete a random label, it is more convenient to do it if the label is placed not by touching but by holding

**Comment by hauke96** [comment]
Hi, thanks for your feature request. So you want to place a note using a long instead of short touch? That sounds like a reasonable feature.

**Comment by OmlineEditor** [comment]
yes, a long press is more convenient

**Comment by hauke96** [comment]
Added the setting. This will be part of the next release (version 1.4.4).
