### ISSUE TITLE
1.4.4 can not install

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hauke96/GeoNotes#66]
Samsung Galaxy S21 5G 
Android 12

i cannot install version 1.4.4, i always get the following message 
![photo1648938743](https://user-images.githubusercontent.com/61406324/161403626-aaba7729-b5ce-4154-b40e-93ac1bc7c364.jpeg)

**Comment by hauke96** [comment]
Ich schreibe hier mal auf Deutsch, ich glaube das geht einfacher ;)

Womit installiert du GeoNotes? Also lädst du per Hand die APK-Datei runter, nutzt du F-Droid oder das Repository von IzzySoft?

Soweit ich sehe ist bei F-Droid noch die alte 1.4.3 Version drin (das dauert bei denen ja immer einige Tage, bis sich das aktualisiert). Habe daher gerade mal die APK-Datei manuell installiert und das hat wunderbar geklappt.

**Comment by mondlicht-und-sterne** [comment]
Hat die App mit Android 12 auch vorher schon funktioniert?

Antwort: die 1.4.3 kann ich installieren.

Womit installiert du GeoNotes? Also lädst du per Hand die APK-Datei runter, nutzt du F-Droid oder das Repository von IzzySoft?

Antwort: natürlich von IzzySoft (meine musthave repo). ging bei mir aber auch nicht. habs manuell probiert, ging auch nicht.

auf meinem lenovo tablet mit android 9 go ging es.

**Comment by hauke96** [comment]
Hm okay, ich schau mal ob ich den Fehler bei mir reproduzieren kann. Da ich kein Android 12 Gerät hier habe, bin ich aber auf Emulatoren angewiesen, ich kann daher nichts versprechen.

**Comment by hauke96** [comment]
Konnte das Problem direkt nachstellen. Hab die Version 1.4.5 gerade veröffentlicht, damit ging es zumindest bei mir im Emulator. Bei IzzySoft wird das dann vermutlich morgen verfügbar sein (ich weiß nicht genau wann er die APKs pullt und bereitstellt).

Wenn du 1.4.5 auch installieren konntest gerne einmal Bescheid geben, dann kann ich das issue hier schließen.

**Comment by mondlicht-und-sterne** [comment]
![IMG_20220403_131356_479](https://user-images.githubusercontent.com/61406324/161425191-54016ded-3e1c-4aef-8f42-127ec29de929.jpg)
![IMG_20220403_131451_545](https://user-images.githubusercontent.com/61406324/161425192-95d72231-9464-4468-ab60-0ed416a417b8.jpg)

@hauke96  

Habs von github gedownloaded, so kann ich zeitnah sagen, das es klappt. 
Danke fürs schnelle fixen.

Und dann wird es bei izzy nach dem update auch klappen.

**Comment by hauke96** [comment]
Wunderbar, dann mache ich hier schon mal zu. Wenn es doch noch Probleme geben sollte, kannst du das issue hier gerne wieder öffnen oder ein neues auf machen.
