### ISSUE TITLE
Does it uses OSM notes API?

### ISSUE THREAD

**Issue by angoca** [hauke96/GeoNotes#68]
I have found this tool which is very useful and easy to take notes while walking. 
However, I have a doubt about it: Does it uses the OSM Notes API: http://api.openstreetmap.org/api/0.6/notes/ ?

I mean, the notes are only for the creator? of they can be automatically exported to OSM and then other can work on them?

**Comment by hauke96** [comment]
Hi, I'm glad you found and like this app :) 

For features that are *not* in GeoNotes, there's a list at the end of the in the [README.md](https://github.com/hauke96/GeoNotes#features-which-will-probably-not-be-added-to-geonotes) file. Creating notes on osm.org is one of those features that are *not* in GeoNotes and probably will never make it. Maybe showing osm.org-notes in GeoNotes (so a read-only mode) will be implemented some day, but who knows.

If you want to create notes you either have to do this manually or use Apps like [StreetComplete](https://github.com/streetcomplete/StreetComplete), which are designed to work with the OSM API.

**Comment by hauke96** [comment]
I close this issue, because there's nothing to do here.
