### ISSUE TITLE
Feature request: import notes from GPX

### ISSUE THREAD

**Issue by urbalazs** [hauke96/GeoNotes#78]
Use case: I have some places in a city what I would like to visit during a trip. It would be nice if I can import the GPX and see the points as notes in this app. I like the UI and the *List of notes* feature where I can see the places as a list.

**Comment by hauke96** [comment]
Thanks for the feature request. The idea is not new, I think now is the point to actually consider this :+1:

**Comment by arielsbecker** [comment]
Maybe it can be expanded to geojson import capabilities too. I use QGIS on desktop and this app on my phone, and having a way to share a geojson will make a lot of peopke's lives easier.

**Comment by k3b** [comment]
you can use https://github.com/k3b/k3b-geoHelper/wiki to implement this.

it supports import-from and export-to for file formats gpx-1.0, gpx-1.1, kml and kmz 

For simple parser examples see https://k3b.github.io/k3b-geoHelper/javadoc/de/k3b/geo/io/gpx/GpxReader.html or https://k3b.github.io/k3b-geoHelper/javadoc/de/k3b/geo/io/gpx/GpxReaderBase.html

**Comment by opk12** [comment]
Maybe the import could be categorized, so it is easily updated (overwritten), or deleted, in the future.

**Comment by nusiloot** [comment]
Hi,
Same request here. I use the app to mark POIs throughout my walks in the city.
Changed my phone this week. 
I knew export feature was available, legitimately thought I'll be able to import my POIs into my new phone.

**Comment by hauke96** [comment]
FYI: In the upcoming GeoNotes 1.7.0 release, it's possible to create backups and also to import backups. This makes it easy to switch phones or restore data of a lost phone or something like that.

For the "import from GPX file" use case: A backup is just a JSON file. One could easily create such a JSON file (the name of it is irrelevant), ZIP it and import it. The file format is quite simple (similar to the GeoJSON files), just take a look at an backup ZIP file.
