### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by urbalazs** [hauke96/GeoNotes#79]
I would like to translate this app into my native language but it seams the [strings.xml](https://github.com/hauke96/GeoNotes/blob/main/app/src/main/res/values/strings.xml) is not up-to-date and most the strings are missing. Can you please update the file?

**Comment by hauke96** [comment]
As of today, I merges a PR regarding the internationalization of this app. Feel free to add your own translation, all relevant strings should be in the `strings.xml` now.
