### ISSUE TITLE
Images are not deleted with notes, they are reused in new notes

### ISSUE THREAD

**Issue by urbalazs** [hauke96/GeoNotes#82]
I had some notes and some of them had image attached. I deleted all notes but the images were still on the phone. If I add notes again, some existing images are attached again. I guess, there is a database table with the linking using note ID and image name, and if the note with the same ID is added again, the linking will be restored.

How to reproduce:

1. Add two notes.
2. Attach an image to the second note.
3. Go to *List of notes* and delete all notes with the trash icon.
4. Check the storage, the image is still there. (problem 1)
5. Add two notes again. The second note will inherit the image taken for the first time. (problem 2)

**Comment by hauke96** [comment]
Thanks for this bug report, never experienced that behavior. I'll look into that.

**Comment by hauke96** [comment]
Just fixed this bug. The fix will be available in the next release. Thanks again for reporting it :)
