### ISSUE TITLE
Italian translations

### ISSUE THREAD

**Issue by RAMAR-RAR** [hauke96/GeoNotes#85]
The text below contains the strings translations based on the hungarian translation file:

<resources>
    <string name="app_name">GeoNotes</string>
    <string name="title_activity_settings" >Impostazioni</string>

    
    <string name="dialog_yes">Sì</string>
    <string name="dialog_no" >No</string>

    
    <string name="toolbar_gps_follow_mode">Modalità segui GPS</string>.
    <string name="toolbar_export">Esporta</string>.
    <string name="toolbar_list_of_notes">Elenco delle note</string>.
    <string name="toolbar_settings">Impostazioni</string>.
    <string name="toolbar_remove_all_notes">Rimuovi tutte le note</string>.

    
    <string name="show_zoom_buttons">Mostra i pulsanti dello zoom</string>.
    <string name="map_scaling_factor">Fattore di scala della mappa</string>.
    <string name="snap_note_to_gps_location">Snap della nota alla posizione GPS</string>.
    <string name="enable_rotating_the_map">Abilita la rotazione della mappa</string>.
    <string name="background_map_cache">Cache di sfondo della mappa</string>.
    <string name="clear">Cancella</string>
    <string name="tap_long_to_create_a_note">Crea una nota con un tocco lungo</string>.
    <string name="feedback">Feedback</string>

    
    <string name="marker_instructions">1. Spostare la mappa\n2. Rilasciare il dito per salvare la posizione</string>.
    <string name="enter_text_for_a_new_note">Inserire il testo della nuova nota:</string>
    <string name="marker_move" >Muovi</string>
    <string name="marker_delete" >Elimina</string>

    
    <string name="gpx_export_failed">Esportazione del file GPX non riuscita</string>.

    
    <string name="delete_all_notes">Eliminare davvero tutte le note? Questo non può essere annullato.</string>
    <string name="create_thumbnail_failed">La creazione della miniatura non è riuscita</string>.
</resources>

**Comment by hauke96** [comment]
Thanks again, I added the translations. Next time, a normal pull request would be nice. You'll also be listed as a contributor then ;)

Some newer strings aren't translated yet, I added TODOs at the locations in the ` values-it/strings.xml` file. Feel free to submit a PR with the translations.
