### ISSUE TITLE
Copright should link to OSM.org

### ISSUE THREAD

**Issue by GoodClover** [hauke96/GeoNotes#9]
This is an extremely unimportant issue, but the copyright notice should link to https://openstreetmap.org or https://www.openstreetmap.org/copyright
Just thought I would point this out.

**Comment by hauke96** [comment]
Hi, you're right and I also came across this.

Unfortunately this is a OsmDroid issue where it's just possible to set an copyright text but not an URL. The whole functionality of this copyright overlay draws a basic string onto a canvas, so the whole text is not a real UI element (s. [here](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/CopyrightOverlay.java#L142)).

Maybe I can add a manual real UI element to hack around this issue, but I'll see if that's possible.

**Comment by GoodClover** [comment]
If it would be a hassle to add it isn't strictly necessary, OSM is *very* laid back about attribution and just having the text should be ok.

You _must_ make it obvious what the license is (`ODbL`).

Linking is just recommended as it makes it a lot easier to attribute without adding extra info to the notice, if it isn't possible they *reccomend* expanding the name out from `OpenStreetMap` to `OpenStreetMap.org`
However, linking is necessary if you are distributing downloads of the data in it's "raw" form. (which you aren't here)

The following string should do:
`© OpenStreetMap.org contributors ODbl`

**Comment by hauke96** [comment]
I added a separate UI element with an hyperlink to [openstreetmap.org/copyright](https://openstreetmap.org/copyright) and released version 1.0.2.
